name: Build and Push Multi-Platform Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      python_version:
        description: "Python version to use (e.g. 3.11, 3.12, 3.13); leave empty to use python:latest"
        required: false
        default: ""
      platforms:
        description: "Comma-separated list of platforms (e.g. linux/amd64, linux/arm64); leave empty to build for linux/amd64,linux/arm64"
        required: false
        default: "linux/amd64,linux/arm64"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set tag and version
        id: vars
        run: |
          if [ -z "${{ github.event.inputs.python_version }}" ]; then
            echo "Using default python:latest"
            echo "PYTHON_VERSION=latest" >> $GITHUB_OUTPUT
            echo "TAG_NAME=latest" >> $GITHUB_OUTPUT
          else
            echo "Using specified python version: ${{ github.event.inputs.python_version }}"
            echo "PYTHON_VERSION=${{ github.event.inputs.python_version }}" >> $GITHUB_OUTPUT
            echo "TAG_NAME=${{ github.event.inputs.python_version }}" >> $GITHUB_OUTPUT
          fi

      - name: Set platforms
        id: platform
        run: |
          if [ -z "${{ github.event.inputs.platforms }}" ]; then
            echo "Using default platforms: linux/amd64,linux/arm64"
            echo "PLATFORMS=linux/amd64,linux/arm64" >> $GITHUB_OUTPUT
          else
            echo "Using specified platforms: ${{ github.event.inputs.platforms }}"
            echo "PLATFORMS=${{ github.event.inputs.platforms }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image for each platform
        run: |
          IFS=', ' read -r -a PLATFORMS <<< "${{ steps.platform.outputs.PLATFORMS }}"
          for PLATFORM in "${PLATFORMS[@]}"; do
            echo "Building image for platform $PLATFORM"
            docker buildx build \
              --platform $PLATFORM \
              --build-arg PYTHON_VERSION=${{ steps.vars.outputs.PYTHON_VERSION }} \
              -t ${{ secrets.DOCKER_USERNAME }}/python-for-bot:${{ steps.vars.outputs.TAG_NAME }}-$PLATFORM \
              --push .
          done
